stages:
  - lint
  - test
  - build
  - package
  - deploy

lint-charts:
  stage: lint
  script:
    - helm lint charts/*

test-scim-service:
  stage: test
  script:
    - docker build -t scim-service-test apps/scim-sync
    - docker run scim-service-test | grep "Hello, SCIM Sync Service!"

build-scim-service:
  stage: build
  script:
    - docker build -t scim-service:latest apps/scim-sync
  only:
    - main

package-scim-service:
  stage: package
  script:
    - docker save scim-service:latest > scim-service.tar
  artifacts:
    paths:
      - scim-service.tar
  only:
    - main

deploy-charts:
  stage: deploy
  script:
    - helm upgrade --install idaas charts/keycloak --namespace idaas
  only:
    - main
