version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: idaas
      POSTGRES_PASSWORD: idaas
      POSTGRES_DB: idaas
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://idaas:idaas@postgres:5432/idaas?schema=public
      JWT_SECRET: change-me
      PORT: 3000
    ports:
      - '3000:3000'
volumes:
  postgres_data:
