replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "18.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
